---
- name: update apt package cache
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: install common packages debian/ubuntu
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - git-core
    - supervisor
  when: ansible_os_family == "Debian"

- name: update locale lang
  locale_gen: name={{ lang }} state=present
  when: ansible_os_family == "Debian"
