---
- name: update apt package cache
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: install common packages debian/ubuntu
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - git-core
    - supervisor

- name: install the locales package
  apt: pkg=locales state=present
  when: ansible_os_family == "Debian"

- name: ensure the locale exists
  command: /usr/sbin/locale-gen {{ locale }}
  when: ansible_os_family == "Debian"

- name: set the locale
  command: /usr/sbin/update-locale LANG={{ locale }} --reset
  when: ansible_os_family == "Debian"
